config/routes.rb
Rails.application.routes.draw do

  get 'greeter/hello' => 'greeter#hello'
  get 'greeter/goodbye'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ['Ganey', 'Bahadur', 'Hisus']
    @name = random_names.sample
    @times = Time.now
    @display_times ||= 0
    @display_times += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formated_time(time)
    time.strftime("%I:%M %p")
  end
end

app/views/greeter/goodbye.html.erb
<h1>I am empty</h1>

app/views/greeter/hello.html.erb
<!-- <% random_names = ['Ganey', 'Bahadur', 'Hisus']%> -->

<h1>Greetings, <%= @name %></h1>
<p>The time now: <%= formated_time(@times) %></p>
<p>Display times: <%= @display_times %></p>

<p><%= link_to "Google", "https://www.google.com" %></p>
<p><%= link_to "GoodBye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>